### ISSUE TITLE
[Question] Could this be used for models other than mBERT (XLM-RoBERTa/mBART/Bloom)?

### ISSUE THREAD

**Issue by GorkaUrbizu** [Geotrend-research/smaller-transformers#3]
Hi! 
Interesting work, and thanks for sharing the scripts.

I was wondering if your code could be directly applied to other multilingual models like encoder based XLM-RoBERTa, decoder based Bloom(mGPT), or encoder-decoder based mBART, since your scripts are build over AutoTokenizer and AutoModel. 
Could your code be used for them without making any adaptation? Have you tried it? 

Regards,
Gorka

**Comment by amineabdaoui** [comment]
Hi @GorkaUrbizu 

We applied the same code to mBERT and Distil-mBERT without any change as both use the same WordPiece tokenizer. 

However, I think that there should be few adaptations to reduce the vocabulary of other tokenizers. 
For example, XLM-R uses a Sentence-Piece tokenizer and even if we can load it inside an AutoTokenizer class, updating the vocabulary may not work in the same way. 

In the current code base [here](https://github.com/Geotrend-research/smaller-transformers/blob/main/reduce_model.py#L54), we only had to write a new vocab.txt file with the selected tokens. 
This works because BERT tokenizes can load their tokens from a vocab.txt file (you can see such file [here](https://huggingface.co/bert-base-multilingual-cased/tree/main)). 
This is not the case for XLM-R tokenizer for example that is usually loaded from [a saved Sentence-Piece BPE model](https://huggingface.co/xlm-roberta-base/tree/main). 

If you want to try something more generic, I can help you with that. 

Apart from this issue in the tokenizer, the rest of the code that reduces the model itself remains the same as the embedding layer is just a torch tensor for all the different models. 

I believe that it would be very interesting to generate smaller versions from XLM-R as its embeddings layers concentrates 70% of the total number of parameters.

**Comment by GorkaUrbizu** [comment]
Hi again,

Thanks for the fast response, and for clarifying my doubts. If the only problem would be loading the tokenizer, it seems doable.
Right now, I won't need this tool for non-BERT architectures, but I might in the future. If that day arrives, I will try to implement a generic version of it and will return with more questions.

Closing Issue.
Gorka
